# -*- coding: utf-8 -*-
"""Fake_news_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BwGJ2rPvSD3jI4U7KrwTJlWRYbsYNIgg
"""

import pandas as pd

df = pd.read_csv("/content/fake_or_real_news.csv")
df.head(10)

df.isnull().sum()

df.columns

df = df.drop(['Unnamed: 0', 'title'], axis=1)

df.head(5)

df['label'] = df['label'].map({
    "FAKE": 0,
    "REAL": 1
})

df.head(5)

df.info()

from sklearn.model_selection import train_test_split

x = df['text']
y = df['label']

x_train, x_test, y_train, y_test = train_test_split(x.tolist(),y.tolist(),test_size=0.2,random_state=42,stratify=y)

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

train_encodings = tokenizer(
    x_train,
    truncation=True,
    padding=True,
    max_length=256
)

test_encodings = tokenizer(
    x_test,
    truncation=True,
    padding=True,
    max_length=256
)

import torch

class NewsDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {k: torch.tensor(v[idx]) for k, v in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels[idx])
        return item

    def __len__(self):
        return len(self.labels)

train_dataset = NewsDataset(train_encodings, y_train)
test_dataset = NewsDataset(test_encodings, y_test)

from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    "bert-base-uncased",
    num_labels=2
)

from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_steps=100,
    save_strategy="no"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    tokenizer=tokenizer
)

trainer.train()

trainer.evaluate()

